#!/usr/bin/env python

'''
Copyright (c) 2011, Yuya Unno
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Yuya Unno nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
'''

from docutils.core import Publisher
from docutils.io import NullOutput

def rst2html(file_path, mode=None):
  pub = Publisher(destination_class=NullOutput)
  pub.set_components('standalone', 'restructuredtext', 'html')
  pub.process_programmatic_settings(None, None, None)
  pub.set_source(None, file_path)
  pub.publish()    
  return unicode(pub.writer.output).encode('utf-8')

if __name__ == '__main__':
    from optparse import OptionParser
    p = OptionParser()
    p.add_option("-p", "--port", type="int", dest="port", default=8080,
                 help="port number")
    (options, args) = p.parse_args()

    from BaseHTTPServer import BaseHTTPRequestHandler
    class MyHandler(BaseHTTPRequestHandler):
        def do_GET(self):
            html = rst2html(args[0])
            self.send_response(200)
            self.end_headers()
            self.wfile.write(html)
            return

    from BaseHTTPServer import HTTPServer
    server = HTTPServer(('', options.port), MyHandler)
    print('Access http://localhost:%i' % options.port)
    print('Type <Ctrl-C> to stop the server')
    server.serve_forever()
